from setuptools import setup

setup(
    name='EZHR',
    version='',
    packages=['env.Lib.distutils', 'env.Lib.encodings', 'env.Lib.importlib', 'env.Lib.collections',
              'env.Lib.site-packages.pip', 'env.Lib.site-packages.pip._vendor',
              'env.Lib.site-packages.pip._vendor.idna', 'env.Lib.site-packages.pip._vendor.pep517',
              'env.Lib.site-packages.pip._vendor.pytoml', 'env.Lib.site-packages.pip._vendor.certifi',
              'env.Lib.site-packages.pip._vendor.chardet', 'env.Lib.site-packages.pip._vendor.chardet.cli',
              'env.Lib.site-packages.pip._vendor.distlib', 'env.Lib.site-packages.pip._vendor.distlib._backport',
              'env.Lib.site-packages.pip._vendor.msgpack', 'env.Lib.site-packages.pip._vendor.urllib3',
              'env.Lib.site-packages.pip._vendor.urllib3.util', 'env.Lib.site-packages.pip._vendor.urllib3.contrib',
              'env.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'env.Lib.site-packages.pip._vendor.urllib3.packages',
              'env.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'env.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'env.Lib.site-packages.pip._vendor.colorama', 'env.Lib.site-packages.pip._vendor.html5lib',
              'env.Lib.site-packages.pip._vendor.html5lib._trie', 'env.Lib.site-packages.pip._vendor.html5lib.filters',
              'env.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'env.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'env.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'env.Lib.site-packages.pip._vendor.lockfile',
              'env.Lib.site-packages.pip._vendor.progress', 'env.Lib.site-packages.pip._vendor.requests',
              'env.Lib.site-packages.pip._vendor.packaging', 'env.Lib.site-packages.pip._vendor.cachecontrol',
              'env.Lib.site-packages.pip._vendor.cachecontrol.caches', 'env.Lib.site-packages.pip._vendor.webencodings',
              'env.Lib.site-packages.pip._vendor.pkg_resources', 'env.Lib.site-packages.pip._internal',
              'env.Lib.site-packages.pip._internal.cli', 'env.Lib.site-packages.pip._internal.req',
              'env.Lib.site-packages.pip._internal.vcs', 'env.Lib.site-packages.pip._internal.utils',
              'env.Lib.site-packages.pip._internal.models', 'env.Lib.site-packages.pip._internal.commands',
              'env.Lib.site-packages.pip._internal.operations', 'env.Lib.site-packages.pytz',
              'env.Lib.site-packages.click', 'env.Lib.site-packages.flask', 'env.Lib.site-packages.flask.json',
              'env.Lib.site-packages.wheel', 'env.Lib.site-packages.wheel.cli', 'env.Lib.site-packages.jinja2',
              'env.Lib.site-packages.pymysql', 'env.Lib.site-packages.pymysql.constants',
              'env.Lib.site-packages.werkzeug', 'env.Lib.site-packages.werkzeug.debug',
              'env.Lib.site-packages.werkzeug.contrib', 'env.Lib.site-packages.aniso8601',
              'env.Lib.site-packages.aniso8601.tests', 'env.Lib.site-packages.aniso8601.builders',
              'env.Lib.site-packages.aniso8601.builders.tests', 'env.Lib.site-packages.markupsafe',
              'env.Lib.site-packages.setuptools', 'env.Lib.site-packages.setuptools.extern',
              'env.Lib.site-packages.setuptools._vendor', 'env.Lib.site-packages.setuptools._vendor.packaging',
              'env.Lib.site-packages.setuptools.command', 'env.Lib.site-packages.sqlalchemy',
              'env.Lib.site-packages.sqlalchemy.ext', 'env.Lib.site-packages.sqlalchemy.ext.declarative',
              'env.Lib.site-packages.sqlalchemy.orm', 'env.Lib.site-packages.sqlalchemy.sql',
              'env.Lib.site-packages.sqlalchemy.pool', 'env.Lib.site-packages.sqlalchemy.util',
              'env.Lib.site-packages.sqlalchemy.event', 'env.Lib.site-packages.sqlalchemy.engine',
              'env.Lib.site-packages.sqlalchemy.testing', 'env.Lib.site-packages.sqlalchemy.testing.suite',
              'env.Lib.site-packages.sqlalchemy.testing.plugin', 'env.Lib.site-packages.sqlalchemy.dialects',
              'env.Lib.site-packages.sqlalchemy.dialects.mssql', 'env.Lib.site-packages.sqlalchemy.dialects.mysql',
              'env.Lib.site-packages.sqlalchemy.dialects.oracle', 'env.Lib.site-packages.sqlalchemy.dialects.sqlite',
              'env.Lib.site-packages.sqlalchemy.dialects.sybase', 'env.Lib.site-packages.sqlalchemy.dialects.firebird',
              'env.Lib.site-packages.sqlalchemy.dialects.postgresql', 'env.Lib.site-packages.sqlalchemy.databases',
              'env.Lib.site-packages.sqlalchemy.connectors', 'env.Lib.site-packages.itsdangerous',
              'env.Lib.site-packages.flask_restful', 'env.Lib.site-packages.flask_restful.utils',
              'env.Lib.site-packages.flask_restful.representations', 'env.Lib.site-packages.pkg_resources',
              'env.Lib.site-packages.pkg_resources.extern', 'env.Lib.site-packages.pkg_resources._vendor',
              'env.Lib.site-packages.pkg_resources._vendor.packaging', 'env.Lib.site-packages.flask_sqlalchemy',
              'venv.Lib.encodings', 'venv.Lib.importlib', 'venv.Lib.collections', 'venv.Lib.site-packages.bs4',
              'venv.Lib.site-packages.bs4.tests', 'venv.Lib.site-packages.bs4.builder', 'venv.Lib.site-packages.jwt',
              'venv.Lib.site-packages.jwt.contrib', 'venv.Lib.site-packages.jwt.contrib.algorithms',
              'venv.Lib.site-packages.idna', 'venv.Lib.site-packages.pytz', 'venv.Lib.site-packages.click',
              'venv.Lib.site-packages.flask', 'venv.Lib.site-packages.flask.json', 'venv.Lib.site-packages.geopy',
              'venv.Lib.site-packages.geopy.extra', 'venv.Lib.site-packages.geopy.geocoders',
              'venv.Lib.site-packages.wheel', 'venv.Lib.site-packages.wheel.cli',
              'venv.Lib.site-packages.google.protobuf', 'venv.Lib.site-packages.google.protobuf.util',
              'venv.Lib.site-packages.google.protobuf.pyext', 'venv.Lib.site-packages.google.protobuf.compiler',
              'venv.Lib.site-packages.google.protobuf.internal',
              'venv.Lib.site-packages.google.protobuf.internal.import_test_package', 'venv.Lib.site-packages.jinja2',
              'venv.Lib.site-packages.certifi', 'venv.Lib.site-packages.chardet', 'venv.Lib.site-packages.chardet.cli',
              'venv.Lib.site-packages.jsonify', 'venv.Lib.site-packages.urllib3', 'venv.Lib.site-packages.urllib3.util',
              'venv.Lib.site-packages.urllib3.contrib', 'venv.Lib.site-packages.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.urllib3.packages', 'venv.Lib.site-packages.urllib3.packages.backports',
              'venv.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'venv.Lib.site-packages.requests',
              'venv.Lib.site-packages.werkzeug', 'venv.Lib.site-packages.werkzeug.debug',
              'venv.Lib.site-packages.werkzeug.contrib', 'venv.Lib.site-packages.aniso8601',
              'venv.Lib.site-packages.aniso8601.tests', 'venv.Lib.site-packages.aniso8601.builders',
              'venv.Lib.site-packages.aniso8601.builders.tests', 'venv.Lib.site-packages.flask_jwt',
              'venv.Lib.site-packages.soupsieve', 'venv.Lib.site-packages.markupsafe',
              'venv.Lib.site-packages.sqlalchemy', 'venv.Lib.site-packages.sqlalchemy.ext',
              'venv.Lib.site-packages.sqlalchemy.ext.declarative', 'venv.Lib.site-packages.sqlalchemy.orm',
              'venv.Lib.site-packages.sqlalchemy.sql', 'venv.Lib.site-packages.sqlalchemy.pool',
              'venv.Lib.site-packages.sqlalchemy.util', 'venv.Lib.site-packages.sqlalchemy.event',
              'venv.Lib.site-packages.sqlalchemy.engine', 'venv.Lib.site-packages.sqlalchemy.testing',
              'venv.Lib.site-packages.sqlalchemy.testing.suite', 'venv.Lib.site-packages.sqlalchemy.testing.plugin',
              'venv.Lib.site-packages.sqlalchemy.dialects', 'venv.Lib.site-packages.sqlalchemy.dialects.mssql',
              'venv.Lib.site-packages.sqlalchemy.dialects.mysql', 'venv.Lib.site-packages.sqlalchemy.dialects.oracle',
              'venv.Lib.site-packages.sqlalchemy.dialects.sqlite', 'venv.Lib.site-packages.sqlalchemy.dialects.sybase',
              'venv.Lib.site-packages.sqlalchemy.dialects.firebird',
              'venv.Lib.site-packages.sqlalchemy.dialects.postgresql', 'venv.Lib.site-packages.sqlalchemy.databases',
              'venv.Lib.site-packages.sqlalchemy.connectors', 'venv.Lib.site-packages.itsdangerous',
              'venv.Lib.site-packages.flask_restful', 'venv.Lib.site-packages.flask_restful.utils',
              'venv.Lib.site-packages.flask_restful.representations', 'venv.Lib.site-packages.geographiclib',
              'venv.Lib.site-packages.geographiclib.test', 'venv.Lib.site-packages.flask_jwt_login',
              'venv.Lib.site-packages.flask_sqlalchemy', 'venv.Lib.site-packages.flask_jwt_extended',
              'venv.Lib.site-packages.virtualenv_support', 'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations'],
    url='',
    license='',
    author='Matthew blackman',
    author_email='',
    description='ezhr backend for proj', install_requires=['flask', 'mysql', 'jsonify']
)
